language: node_js
node_js:
- stable
cache:
  directories:
  - node_modules
branches:
  only:
  - master
addons:
  ssh_known_hosts:
  - compelcode.com #受信主机，你的Linux服务器ip
before_install:
- openssl aes-256-cbc -K $encrypted_04674a2f3de9_key -iv $encrypted_04674a2f3de9_iv
  -in id_rsa.enc -out ~/.ssh/id_rsa -d
- chmod 600 ~/.ssh/id_rsa
after_success:
- ssh -p 2022 travis@compelcode.com 'cd /www/zhangxu/zansder-site-next-node/ && git pull && pm2 reload app'
